declare the inline function opt_finished static
an `inline int opt_finished` causes GCC to spew this error when used
with -std=gnu99:

libcoap/option.c:165: undefined reference to `opt_finished'

Signed-off-by: Olaf Bergmann <bergmann@tzi.org>