debug.c: replace 'in_port_t' with 'uint16_t'
`in_port_t` might be hidden under `_GNU_SOURCE` feature test macro, which
is not defined at the top of the file. This happens with newlib build with
Zephyr SDK and with Zephyr RTOS. As a result following build error occurs:

  /libcoap/src/coap_debug.c: In function 'coap_print_addr':
  /libcoap/src/coap_debug.c:189:3: error: unknown type name 'in_port_t'; \
                                              did you mean 'io_port_t'?
    189 |   in_port_t port;
        |   ^~~~~~~~~
        |   io_port_t

Workaround that issue by replacing `in_port_t` with `uint16_t`, as that is
the only place where former typedef was used.

Signed-off-by: Marcin Niestroj <m.niestroj@emb.dev>